
def on_on_update():
    if hero.vy < 0:
        Hops_and_Paw.set_image(img("""
            . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . .
            . . . . . . . . . . . f . . . .
            . . . . . . . . . . . f f f . .
            . . . . . . . . . . . f f 5 f .
            . . . f . . . . . . f f f f f .
            . . . f . . . . . . f f f f . .
            . . f f . . . . . f f f . . . .
            . . f . . . . . . f f f f f f f
            . . f . . . . . f f f f . . . .
            . . f f . . . f f f f f f f f .
            . . . f f f f f f f . . . . . .
            . . . . . . f f f . . . . . . .
            . . . . . f f . f . . . . . . .
            . . . . . f . . f . . . . . . .
            . . . . . f . . . . . . . . . .
        """))
    elif Hops_and_Paw.vy > 0:
        Hops_and_Paw.set_image(img("""
            . . . . . . . f . . . . . . . .
            . . . . . . f . . . . . . . . .
            . . . . . f f . . . . . . . . .
            . . . . . f . . . . . . . . . .
            . . . . . f . . . . . . . . . .
            . . . . . f f . . . . . . . . .
            . . . . f f f f . . . . . . . .
            . . . . f f f f . . . . . . . .
            . . . . f f f f f . . . . . . .
            . . . . f . f f f f . . f . . .
            . . . . f . f f f f f f f f f .
            . . . . f . f . f f f f f f 5 f
            . . . . . . . . f f f f f f f f
            . . . . . . . . f . f . . . . .
            . . . . . . . . f . f . . . . .
            . . . . . . . . f . f f . . . .
        """))
    elif Hops_and_Paw.x % 2 == 0:
        Hops_and_Paw.set_image(img("""
            ..............ffffff....
            .............f2feeeeff..
            ............f222feeeeff.
            ............feeeeffeeef.
            ...........fe2222eeffff.
            ...........f2effff222ef.
            ...........fffeeefffffff
            ...........fee44fbe44eff
            ............feddf14d4eef
            .............fdddd4eeef.
            .............fe444eddf..
            .............ccc22eddf..
            .............cdc22fee...
            ............cddc4444f...
            ...........cddcfffff....
            ..........cddc..fff.....
            ..........cdc...........
            ..........cc............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
        """))
    else:
        Hops_and_Paw.set_image(img("""
            ......ffff..............
            ....fff22fff............
            ...fff2222fff...........
            ..fffeeeeeefff..........
            ..ffe222222eef..........
            ..fe2ffffff2ef..........
            ..ffffeeeeffff......ccc.
            .ffefbf44fbfeff....cddc.
            .ffefbf44fbfeff...cddc..
            .fee4dddddd4eef.ccddc...
            fdfeeddddd4eeffecddc....
            fbffee4444ee4fddccc.....
            fbf4f222222f1edde.......
            fcf.f222222f44ee........
            .ff.f445544f............
            ....ffffffff............
            .....ff..ff.............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
        """))
